
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ItemsMenu from "./_components/items-menu";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Providers from "./providers";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const queryClient = new QueryClient()

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
        lang="en"
        className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
      >
        <body className="min-h-full flex flex-col">
          <div className="flex">
            <div className="flex flex-col bg-primary-color min-h-screen w-75 items-center justify-center border-r border-white/10">
              <h1 className="font-medium text-2xl mb-8 mt-5 text-white">Wtach Tower</h1>
              <ItemsMenu />
            </div>
            <Providers><div className="min-h-full w-full bg-secondary-color">{children}</div></Providers>
          </div>
        </body>
      </html>
  );
}
